### ISSUE TITLE
question concerning an archived repository

### ISSUE THREAD

**Issue by doctashay** [doge/image-host#1]
hey there, I am SO sorry to use the issue tracker for this purpose but I have a question regarding the MongoDB DayZServlet you posted and i'm afraid you're the only one who can help me out, i just had a couple questions regarding documentation and would love if you could reach out. i'm hoping you could provide a little more documentation on the install process for me, because as it is, the Python server can intercept the api routes/calls the engine makes, but does not commit those changes to a database. I have my collection "players" stored in database "dayz" and still am not getting new data to save correctly, is there a specific document or dataset I need to add into the empty collection? I have my own fork of this project I've created on my page and would really appreciate any insight you have to offer as all of the existing JS/PHP/SQL implemenations of the servlet are no longer hosted anymore or not functional for the particular version I am working with. Would appreciate any guidance and again my deepest apologies for having to use this as a channel for communication.

**Comment by doge** [comment]
When correctly setting up your instance of MongoDB, the pymongo library I'm using will create the database and collections automatically. You just have to make sure your instance is setup and connecting correctly. I'll un-archive the repository incase you have any more issues.
